### ISSUE TITLE
Checklist overlapping input

### ISSUE THREAD

**Issue by MicahBredenhorst** [Y1chenYao/typora-mint-theme#11]
When exporting the mint theme to pdf the custom style input overlaps another style.
As seen in the image below:
![image](https://user-images.githubusercontent.com/32055847/158751809-7ae7889e-4130-4023-a265-560c2d8e4c98.png)

**System Information**:
- Windows 10
- PDF viewer: Firefox Developer / Chrome
- Typora version 1.1.5
- Mint theme version: most recent as of 17-03-2022

**Comment by Y1chenYao** [comment]
![image](https://user-images.githubusercontent.com/68068854/163699251-9ef65942-e1b0-44b4-b1ba-788725369bd2.png)
Hi! Thank you for pointing that out. I hope that the new commit has fixed it.

**Comment by MicahBredenhorst** [comment]
Just tested it and it seems to be fixed :+1:
