### ISSUE TITLE
Dark模式

### ISSUE THREAD

**Issue by Tec-Ma** [Y1chenYao/typora-mint-theme#2]
![`R_8B ZKZ U}(%H{NBM1WPV](https://user-images.githubusercontent.com/67678343/129827648-1ee030e6-3bec-4775-92e4-78c19b310b22.png)
![9$C9E%~ D1~{ 1RD(PLJTVP](https://user-images.githubusercontent.com/67678343/129827653-13703b34-b1fb-4197-b1b6-270d551c6eeb.png)

老哥，这Dark模式变色好像没变全，用的是你最新发的。

**Comment by Y1chenYao** [comment]
debug好了

**Comment by Tec-Ma** [comment]
好了，牛逼，感谢。
