### ISSUE TITLE
Justified text

### ISSUE THREAD

**Issue by redriel** [Y1chenYao/typora-mint-theme#3]
Hello, I tried to overwrite the CSS in order to justify the text using this theme.
Usually overwriting works with other themes, but with the mint theme the text remains right aligned.
Do you have any suggestions?

(谷歌翻译)
您好，我尝试覆盖 CSS 以证明使用此主题的文本的合理性。
通常覆盖适用于其他主题，但对于薄荷主题，文本保持右对齐。
你有什么建议吗？

**Comment by Y1chenYao** [comment]
What content do you want to justify? I don't really know how to justify the contents in the text body.

**Comment by redriel** [comment]
Hi, I figured out how to justify the text with your theme. I simply overrode some properties in the base.user.css as it follows:
```
#write {
  max-width: 800px !important;
  text-align: justify !important;
}

#write p{
	text-align:justify !important;
}
```
