### ISSUE TITLE
Too crowded between-line space for # 1 title

### ISSUE THREAD

**Issue by Williams-Ren** [Y1chenYao/typora-mint-theme#6]
![image](https://user-images.githubusercontent.com/45218090/142490413-d5f6a490-016b-4c59-934c-c9d45d8b5b9d.png)

如图，当一级标题超过一行后会因为行间距过窄而导致字符碰撞。

**Comment by Y1chenYao** [comment]
It should now be fixed.
![image](https://user-images.githubusercontent.com/68068854/142552698-4027e061-1d03-483b-854f-0484c17dd6a1.png)

**Comment by Williams-Ren** [comment]
Thank you! The issue has been fixed.
