### ISSUE TITLE
about code quote

### ISSUE THREAD

**Issue by classmatezhu** [Y1chenYao/typora-mint-theme#7]
首先，很感谢您开发的这个主题。真的非常好看和舒适。但是不知道为什么，代码块的第一行，颜色和其他行不一样。
![code](https://user-images.githubusercontent.com/20785826/143017142-5808a6f2-7de1-4277-a2c2-1e55ac3f2245.png)

**Comment by Y1chenYao** [comment]
目前更新的commit删除了这个设置
